### ISSUE TITLE
Annotations not aligned

### ISSUE THREAD

**Issue by Stakaitis** [webermarcolivier/statannot#26]
First of all - a very useful tool, thank You

For some reason, the annotations are not aligned for me and I can't figure why.
I'm using the code below and the annotations are far to the right of the boxplot.
Running the code on Anacondas 1.9.7 JupyterLab 1.1.4 Python 3.7.3
Do You know where the problem could be?
![Screenshot 2019-10-27 at 10 35 40](https://user-images.githubusercontent.com/46847401/67632590-b1ee7d80-f8a5-11e9-8217-993b46fa8485.png)

`ax = sns.boxplot(data=df[['ACTB','GAPDH','HPRT1']])
fig = plt.gcf()
test_results = add_stat_annotation(ax, df, box_pairs=[('ACTB','GAPDH'), ('ACTB','HPRT1'), ('GAPDH','HPRT1')],
                                  test='t-test_ind', text_format='star', loc='outside', verbose=1)`

**Comment by webermarcolivier** [comment]
One limitation of the tool is that you need to pass the _exact same arguments_ `data`, `x`, `y`, `hue` and `order` to the seaborn `boxplot` function than to the `add_stat_annotation` function, otherwise the x position of the boxes will not be correctly computed. I suspect that the column order of the dataframe passed as `data` argument are different in both functions. Could you try passing the same exact dataframe?

**Comment by Stakaitis** [comment]
> One limitation of the tool is that you need to pass the _exact same arguments_ `data`, `x`, `y`, `hue` and `order` to the seaborn `boxplot` function than to the `add_stat_annotation` function, otherwise the x position of the boxes will not be correctly computed. I suspect that the column order of the dataframe passed as `data` argument are different in both functions. Could you try passing the same exact dataframe?

It worked! Although I should have figure it myself - when You pointed it out it seems so obvious. Thank You
![Screenshot 2019-10-28 at 14 06 39](https://user-images.githubusercontent.com/46847401/67680741-2ef42280-f98c-11e9-9256-a683b5d3d38e.png)
